FROM alpine:3.20.0

################################
# Karaf HyperIoT Microservices #
################################

ARG KARAF_MICROSERVICES_VERSION=1.0.0

ENV KARAF_USER karaf
ENV KARAF_UID 8181
ENV KARAF_VERSION 4.2.6
ENV JAVA_MAX_MEM 256m
ENV KARAF_EXEC exec
ENV KARAF_FOLDER /opt/apache-karaf-microservices
ENV KARAF_TAR_FILE karaf-microservices-${KARAF_MICROSERVICES_VERSION}.tar.gz
ENV DB_SERVER_NAME host.docker.internal
ENV DB_SERVER_PORT 5432
ENV DB_SERVER_USER hyperiot
ENV DB_SERVER_PASSWORD hyperiot
ENV DB_SERVER_JDBC_DRIVER org.postgresql.Driver
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH=/usr/lib/jvm/java-17-openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Directory for external module bundles (aligned with Distribution-spring-app)
ENV MODULES_PATH=/opt/modules
# File con la lista moduli (può essere sovrascritto con volume o build arg)
ENV MODULES_LIST_FILE=/opt/config/modules.list
# Nome della feature generata
ENV FEATURE_NAME=dynamic-modules
ENV FEATURE_VERSION=1.0.0

# --- Installing required packages ---
RUN apk update && apk add --no-cache openssh openjdk17 java-cacerts jq curl

# --- Extracting Karaf ---
COPY ./target/$KARAF_TAR_FILE /opt/
RUN mkdir /opt/karaf
RUN addgroup -g $KARAF_UID -S $KARAF_USER && adduser -u $KARAF_UID -G $KARAF_USER -S -D $KARAF_USER
RUN tar --strip-components=1 -C /opt/karaf -xzf /opt/$KARAF_TAR_FILE \
    && rm /opt/$KARAF_TAR_FILE \
    && chown -R $KARAF_USER:$KARAF_USER /opt/karaf \
    && chmod 700 /opt/karaf/data
RUN rm -rf /opt/karaf/system/it

# --- Directory per config esterna e moduli ---
RUN mkdir -p /opt/config "${MODULES_PATH}" \
    && chown -R $KARAF_USER:$KARAF_USER /opt/config "${MODULES_PATH}"

# --- Copia entrypoint ---
COPY --chown=$KARAF_USER:$KARAF_USER entrypoint.sh /opt/entrypoint.sh
RUN chmod +x /opt/entrypoint.sh

EXPOSE 1099 8101 44444 8181 1883 61616 61614
USER $KARAF_USER

ENTRYPOINT ["/opt/entrypoint.sh"]
CMD ["/opt/karaf/bin/karaf", "run", "debug", "clean"]